### ISSUE TITLE
Fatal error after installation

### ISSUE THREAD

**Issue by antever** [arjunsuresh/q2a-categoryexperts#1]
Fatal error: Call to undefined function qa_db_points_option_names() in .../qa-plugin/q2a-categoryexperts-master/qa-catexp-admin.php on line 36

The error appears when:

- trying to open plugin page in admin control panel
- trying to add the widget to all possible pages and opening one of them

Q2A version 1.7.4
Q2A database version: 59
PHP version:	5.4.45
MySQL version:	5.5.51-38.2

**Comment by arjunsuresh** [comment]
Oh. Can you do a "git pull" or redownload and try?

**Comment by antever** [comment]
That's odd. It's working now. Thank you!

**Comment by antever** [comment]
By the way, the first time it didn't request a database initialization right away.

**Comment by arjunsuresh** [comment]
great. I added an include file explicitly now - guess in my system it was included by some other plugin and hence no error.
