### ISSUE TITLE
Problem detected

### ISSUE THREAD

**Issue by kelklope** [arjunsuresh/q2a-categoryexperts#2]
The plugin doesn't work it shows a lot of errors

On the admin area it shows : Notice: Undefined index: rows in /home/user/public_html/qa-include/qa-theme-base.php on line 1284

**Comment by arjunsuresh** [comment]
I dont think that notice is coming from this plugin as "rows" is not used in this.

**Comment by iamdand** [comment]
I second this issue... This is the records from my log

[:error] [pid 58995] [client 127.0.0.1:61041] PHP Notice:  Undefined index: rows in /Users/user/Sites/MySite/qa/qa-include/qa-theme-base.php on line 1284, referer: http://MySite/qa/admin/plugins?show=c98598832f965644a702f39255d59225

Code from the file (qa-inclue/qa-theme-base.php) reads:

public function form_text_multi_row($field, $style)
{
	$this->output('<textarea '.@$field['tags'].' rows="'.(int)$field['rows'].'" cols="40" class="qa-form-'.$style.'-text">'.@$field['value'].'</textarea>');
}

**Comment by arjunsuresh** [comment]
:O Which theme are you using? I have tried on both snowflat and Donut themes and there are no warnings being reported. Can you try disabling the plugin in admin area and see if the warning disappears?

**Comment by arjunsuresh** [comment]
The error was in admin page due to "rows" missing in the form for textarea. Fixed in the minor version change.
