### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by gturri** [arjunsuresh/q2a-categoryexperts#4]
I'm giving this plugin a try and I'm having some trouble understanding how it works.
I copied the directory in my `qa-plugin` directory, I then launched the upgrade of the database from the admin panel, and I then clicked on `Recalculate` from the admin panel; but I still don't see how it works. (for what it worth: my question2answer instance is at https://zerowasteparis.fr/questions ; I don't know if it helps).
I may be missing something obvious, but I may not be the only one missing it, so it could be useful to add a README to add this information

**Comment by gturri** [comment]
Actually I see that the description of this repo points at https://gateoverflow.in/questions but I don't see on this website where is displayed top scoring users per category. Perhaps just explaning it would be enough to close this bug report.

**Comment by arjunsuresh** [comment]
Hi, Actually this plugin is mostly retired. The main reason is this is expensive on the site. The way points are working on Q2A - they get updated on each action. But unfortunately there is no support to know the category of the post which caused the update. This can be done easily by a core change; but I didnt think that is worth the try.

**Comment by gturri** [comment]
ok. Thank you for this clarification.
(don't hesitate to let me know if you manage to get this plugin alive and kicking: though I won't be able to take the time to dive into the code to enhance it, I believe this feature is interesting)
